# Generated by Django 3.1.3 on 2020-11-10 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_disciplina', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Tcc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('resumo', models.TextField()),
                ('introducao', models.TextField()),
                ('referencial_teorico', models.TextField()),
                ('metodologia', models.TextField()),
                ('analise_resultados', models.TextField()),
                ('conclusoes', models.TextField()),
                ('referencia_bibliografica', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('matricula', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=50)),
                ('titulo_graduacao', models.CharField(max_length=70)),
                ('tipo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_bd.tipo_usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_tcc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tcc_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_bd.tcc')),
                ('matricula_fk', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api_bd.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_disciplina_fk', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api_bd.disciplina')),
                ('matricula_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_bd.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Orientacoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('id_tcc_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_bd.tcc')),
            ],
        ),
        migrations.CreateModel(
            name='Curso_disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_curso_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_bd.curso')),
                ('id_disciplina_fk', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api_bd.disciplina')),
            ],
        ),
    ]
